/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TernosRouteImport } from './routes/ternos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CamisariaRouteImport } from './routes/camisaria'
import { Route as CalcadosRouteImport } from './routes/calcados'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as AcessoriosRouteImport } from './routes/acessorios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FornecedoresPedidoRouteImport } from './routes/fornecedores.pedido'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TernosRoute = TernosRouteImport.update({
  id: '/ternos',
  path: '/ternos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CamisariaRoute = CamisariaRouteImport.update({
  id: '/camisaria',
  path: '/camisaria',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcadosRoute = CalcadosRouteImport.update({
  id: '/calcados',
  path: '/calcados',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosRoute = AcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresPedidoRoute = FornecedoresPedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => FornecedoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/acessos': typeof AcessosRoute
  '/calcados': typeof CalcadosRoute
  '/camisaria': typeof CamisariaRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRouteWithChildren
  '/login': typeof LoginRoute
  '/perfis': typeof PerfisRoute
  '/produtos': typeof ProdutosRoute
  '/ternos': typeof TernosRoute
  '/usuarios': typeof UsuariosRoute
  '/fornecedores/pedido': typeof FornecedoresPedidoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/acessos': typeof AcessosRoute
  '/calcados': typeof CalcadosRoute
  '/camisaria': typeof CamisariaRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRouteWithChildren
  '/login': typeof LoginRoute
  '/perfis': typeof PerfisRoute
  '/produtos': typeof ProdutosRoute
  '/ternos': typeof TernosRoute
  '/usuarios': typeof UsuariosRoute
  '/fornecedores/pedido': typeof FornecedoresPedidoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/acessos': typeof AcessosRoute
  '/calcados': typeof CalcadosRoute
  '/camisaria': typeof CamisariaRoute
  '/categorias': typeof CategoriasRoute
  '/clientes': typeof ClientesRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRouteWithChildren
  '/login': typeof LoginRoute
  '/perfis': typeof PerfisRoute
  '/produtos': typeof ProdutosRoute
  '/ternos': typeof TernosRoute
  '/usuarios': typeof UsuariosRoute
  '/fornecedores/pedido': typeof FornecedoresPedidoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessorios'
    | '/acessos'
    | '/calcados'
    | '/camisaria'
    | '/categorias'
    | '/clientes'
    | '/conta'
    | '/dashboard'
    | '/estoque'
    | '/fornecedores'
    | '/login'
    | '/perfis'
    | '/produtos'
    | '/ternos'
    | '/usuarios'
    | '/fornecedores/pedido'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessorios'
    | '/acessos'
    | '/calcados'
    | '/camisaria'
    | '/categorias'
    | '/clientes'
    | '/conta'
    | '/dashboard'
    | '/estoque'
    | '/fornecedores'
    | '/login'
    | '/perfis'
    | '/produtos'
    | '/ternos'
    | '/usuarios'
    | '/fornecedores/pedido'
  id:
    | '__root__'
    | '/'
    | '/acessorios'
    | '/acessos'
    | '/calcados'
    | '/camisaria'
    | '/categorias'
    | '/clientes'
    | '/conta'
    | '/dashboard'
    | '/estoque'
    | '/fornecedores'
    | '/login'
    | '/perfis'
    | '/produtos'
    | '/ternos'
    | '/usuarios'
    | '/fornecedores/pedido'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoriosRoute: typeof AcessoriosRoute
  AcessosRoute: typeof AcessosRoute
  CalcadosRoute: typeof CalcadosRoute
  CamisariaRoute: typeof CamisariaRoute
  CategoriasRoute: typeof CategoriasRoute
  ClientesRoute: typeof ClientesRoute
  ContaRoute: typeof ContaRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  FornecedoresRoute: typeof FornecedoresRouteWithChildren
  LoginRoute: typeof LoginRoute
  PerfisRoute: typeof PerfisRoute
  ProdutosRoute: typeof ProdutosRoute
  TernosRoute: typeof TernosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ternos': {
      id: '/ternos'
      path: '/ternos'
      fullPath: '/ternos'
      preLoaderRoute: typeof TernosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camisaria': {
      id: '/camisaria'
      path: '/camisaria'
      fullPath: '/camisaria'
      preLoaderRoute: typeof CamisariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcados': {
      id: '/calcados'
      path: '/calcados'
      fullPath: '/calcados'
      preLoaderRoute: typeof CalcadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios': {
      id: '/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/pedido': {
      id: '/fornecedores/pedido'
      path: '/pedido'
      fullPath: '/fornecedores/pedido'
      preLoaderRoute: typeof FornecedoresPedidoRouteImport
      parentRoute: typeof FornecedoresRoute
    }
  }
}

interface FornecedoresRouteChildren {
  FornecedoresPedidoRoute: typeof FornecedoresPedidoRoute
}

const FornecedoresRouteChildren: FornecedoresRouteChildren = {
  FornecedoresPedidoRoute: FornecedoresPedidoRoute,
}

const FornecedoresRouteWithChildren = FornecedoresRoute._addFileChildren(
  FornecedoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoriosRoute: AcessoriosRoute,
  AcessosRoute: AcessosRoute,
  CalcadosRoute: CalcadosRoute,
  CamisariaRoute: CamisariaRoute,
  CategoriasRoute: CategoriasRoute,
  ClientesRoute: ClientesRoute,
  ContaRoute: ContaRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  FornecedoresRoute: FornecedoresRouteWithChildren,
  LoginRoute: LoginRoute,
  PerfisRoute: PerfisRoute,
  ProdutosRoute: ProdutosRoute,
  TernosRoute: TernosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
