/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TernosRouteImport } from './routes/ternos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as MeuPerfilRouteImport } from './routes/meu-perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CamisariaRouteImport } from './routes/camisaria'
import { Route as CalcadosRouteImport } from './routes/calcados'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as AcessoriosRouteImport } from './routes/acessorios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedidosCompraHistoricoRouteImport } from './routes/pedidos-compra.historico'
import { Route as PagamentosHistoricoRouteImport } from './routes/pagamentos.historico'
import { Route as PagamentosConfiguracoesRouteImport } from './routes/pagamentos.configuracoes'
import { Route as FornecedoresPedidoRouteImport } from './routes/fornecedores_.pedido'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TernosRoute = TernosRouteImport.update({
  id: '/ternos',
  path: '/ternos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPerfilRoute = MeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CamisariaRoute = CamisariaRouteImport.update({
  id: '/camisaria',
  path: '/camisaria',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcadosRoute = CalcadosRouteImport.update({
  id: '/calcados',
  path: '/calcados',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosRoute = AcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosCompraHistoricoRoute = PedidosCompraHistoricoRouteImport.update({
  id: '/pedidos-compra/historico',
  path: '/pedidos-compra/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosHistoricoRoute = PagamentosHistoricoRouteImport.update({
  id: '/pagamentos/historico',
  path: '/pagamentos/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosConfiguracoesRoute = PagamentosConfiguracoesRouteImport.update({
  id: '/pagamentos/configuracoes',
  path: '/pagamentos/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresPedidoRoute = FornecedoresPedidoRouteImport.update({
  id: '/fornecedores_/pedido',
  path: '/fornecedores/pedido',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/acessos': typeof AcessosRoute
  '/calcados': typeof CalcadosRoute
  '/camisaria': typeof CamisariaRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/empresa': typeof EmpresaRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/perfis': typeof PerfisRoute
  '/produtos': typeof ProdutosRoute
  '/ternos': typeof TernosRoute
  '/usuarios': typeof UsuariosRoute
  '/fornecedores/pedido': typeof FornecedoresPedidoRoute
  '/pagamentos/configuracoes': typeof PagamentosConfiguracoesRoute
  '/pagamentos/historico': typeof PagamentosHistoricoRoute
  '/pedidos-compra/historico': typeof PedidosCompraHistoricoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/acessos': typeof AcessosRoute
  '/calcados': typeof CalcadosRoute
  '/camisaria': typeof CamisariaRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/empresa': typeof EmpresaRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/perfis': typeof PerfisRoute
  '/produtos': typeof ProdutosRoute
  '/ternos': typeof TernosRoute
  '/usuarios': typeof UsuariosRoute
  '/fornecedores/pedido': typeof FornecedoresPedidoRoute
  '/pagamentos/configuracoes': typeof PagamentosConfiguracoesRoute
  '/pagamentos/historico': typeof PagamentosHistoricoRoute
  '/pedidos-compra/historico': typeof PedidosCompraHistoricoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessorios': typeof AcessoriosRoute
  '/acessos': typeof AcessosRoute
  '/calcados': typeof CalcadosRoute
  '/camisaria': typeof CamisariaRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/clientes': typeof ClientesRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/empresa': typeof EmpresaRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/login': typeof LoginRoute
  '/meu-perfil': typeof MeuPerfilRoute
  '/perfis': typeof PerfisRoute
  '/produtos': typeof ProdutosRoute
  '/ternos': typeof TernosRoute
  '/usuarios': typeof UsuariosRoute
  '/fornecedores_/pedido': typeof FornecedoresPedidoRoute
  '/pagamentos/configuracoes': typeof PagamentosConfiguracoesRoute
  '/pagamentos/historico': typeof PagamentosHistoricoRoute
  '/pedidos-compra/historico': typeof PedidosCompraHistoricoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessorios'
    | '/acessos'
    | '/calcados'
    | '/camisaria'
    | '/categorias'
    | '/checkout'
    | '/clientes'
    | '/conta'
    | '/dashboard'
    | '/empresa'
    | '/estoque'
    | '/fornecedores'
    | '/login'
    | '/meu-perfil'
    | '/perfis'
    | '/produtos'
    | '/ternos'
    | '/usuarios'
    | '/fornecedores/pedido'
    | '/pagamentos/configuracoes'
    | '/pagamentos/historico'
    | '/pedidos-compra/historico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessorios'
    | '/acessos'
    | '/calcados'
    | '/camisaria'
    | '/categorias'
    | '/checkout'
    | '/clientes'
    | '/conta'
    | '/dashboard'
    | '/empresa'
    | '/estoque'
    | '/fornecedores'
    | '/login'
    | '/meu-perfil'
    | '/perfis'
    | '/produtos'
    | '/ternos'
    | '/usuarios'
    | '/fornecedores/pedido'
    | '/pagamentos/configuracoes'
    | '/pagamentos/historico'
    | '/pedidos-compra/historico'
  id:
    | '__root__'
    | '/'
    | '/acessorios'
    | '/acessos'
    | '/calcados'
    | '/camisaria'
    | '/categorias'
    | '/checkout'
    | '/clientes'
    | '/conta'
    | '/dashboard'
    | '/empresa'
    | '/estoque'
    | '/fornecedores'
    | '/login'
    | '/meu-perfil'
    | '/perfis'
    | '/produtos'
    | '/ternos'
    | '/usuarios'
    | '/fornecedores_/pedido'
    | '/pagamentos/configuracoes'
    | '/pagamentos/historico'
    | '/pedidos-compra/historico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoriosRoute: typeof AcessoriosRoute
  AcessosRoute: typeof AcessosRoute
  CalcadosRoute: typeof CalcadosRoute
  CamisariaRoute: typeof CamisariaRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRoute
  ClientesRoute: typeof ClientesRoute
  ContaRoute: typeof ContaRoute
  DashboardRoute: typeof DashboardRoute
  EmpresaRoute: typeof EmpresaRoute
  EstoqueRoute: typeof EstoqueRoute
  FornecedoresRoute: typeof FornecedoresRoute
  LoginRoute: typeof LoginRoute
  MeuPerfilRoute: typeof MeuPerfilRoute
  PerfisRoute: typeof PerfisRoute
  ProdutosRoute: typeof ProdutosRoute
  TernosRoute: typeof TernosRoute
  UsuariosRoute: typeof UsuariosRoute
  FornecedoresPedidoRoute: typeof FornecedoresPedidoRoute
  PagamentosConfiguracoesRoute: typeof PagamentosConfiguracoesRoute
  PagamentosHistoricoRoute: typeof PagamentosHistoricoRoute
  PedidosCompraHistoricoRoute: typeof PedidosCompraHistoricoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ternos': {
      id: '/ternos'
      path: '/ternos'
      fullPath: '/ternos'
      preLoaderRoute: typeof TernosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-perfil': {
      id: '/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof MeuPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camisaria': {
      id: '/camisaria'
      path: '/camisaria'
      fullPath: '/camisaria'
      preLoaderRoute: typeof CamisariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcados': {
      id: '/calcados'
      path: '/calcados'
      fullPath: '/calcados'
      preLoaderRoute: typeof CalcadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios': {
      id: '/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos-compra/historico': {
      id: '/pedidos-compra/historico'
      path: '/pedidos-compra/historico'
      fullPath: '/pedidos-compra/historico'
      preLoaderRoute: typeof PedidosCompraHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos/historico': {
      id: '/pagamentos/historico'
      path: '/pagamentos/historico'
      fullPath: '/pagamentos/historico'
      preLoaderRoute: typeof PagamentosHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos/configuracoes': {
      id: '/pagamentos/configuracoes'
      path: '/pagamentos/configuracoes'
      fullPath: '/pagamentos/configuracoes'
      preLoaderRoute: typeof PagamentosConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores_/pedido': {
      id: '/fornecedores_/pedido'
      path: '/fornecedores/pedido'
      fullPath: '/fornecedores/pedido'
      preLoaderRoute: typeof FornecedoresPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoriosRoute: AcessoriosRoute,
  AcessosRoute: AcessosRoute,
  CalcadosRoute: CalcadosRoute,
  CamisariaRoute: CamisariaRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRoute,
  ClientesRoute: ClientesRoute,
  ContaRoute: ContaRoute,
  DashboardRoute: DashboardRoute,
  EmpresaRoute: EmpresaRoute,
  EstoqueRoute: EstoqueRoute,
  FornecedoresRoute: FornecedoresRoute,
  LoginRoute: LoginRoute,
  MeuPerfilRoute: MeuPerfilRoute,
  PerfisRoute: PerfisRoute,
  ProdutosRoute: ProdutosRoute,
  TernosRoute: TernosRoute,
  UsuariosRoute: UsuariosRoute,
  FornecedoresPedidoRoute: FornecedoresPedidoRoute,
  PagamentosConfiguracoesRoute: PagamentosConfiguracoesRoute,
  PagamentosHistoricoRoute: PagamentosHistoricoRoute,
  PedidosCompraHistoricoRoute: PedidosCompraHistoricoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
